Repository QAZIMAAZARSHAD/Income-Tax-Calculator, pull requests merged in 2021-06, with the labels that each got.

#14 Wrong result when taxable income becomes too large
  FinalProject--Python.py
Labels: LGMSOC21, 🟧 Level3

#13 created a yes/no pop-up window when exiting application #8
  FinalProject--Python.py
  tempCodeRunnerFile.py
Labels: LGMSOC21, 🟨 Level2

#21 Solved the issue of Resizing the window
  FinalProject--Python.py
Labels: LGMSOC21, 🟩 Level1

#18 (UPDATED)Disable maximise/minimise option from "Check Tax Scheme" Pop-Up
  FinalProject--Python.py
Labels: LGMSOC21, 🟩 Level1

#34 Cursor pointer on hover buttons
  FinalProject--Python.py
Labels: LGMSOC21, 🟩 Level1

#44 Added clear button
  FinalProject--Python.py
Labels: LGMSOC21, 🟨 Level2

#47 Added User details Button
  FinalProject--Python.py
Labels: LGMSOC21, 🟨 Level2

#50 Updated the tax issue
  FinalProject--Python.py
Labels: LGMSOC21, 🟨 Level2

#52 added links to gifs
  README.md
Labels: LGMSOC21, 🟩 Level1

#56 Updated screenshots in README file.
  README.md
Labels: LGMSOC21, 🟩 Level1

#66 Added Badges
  README.md
Labels: LGMSOC21, 🟩 Level1

#64 Fixed Validation Issue
  FinalProject--Python.py
Labels: LGMSOC21, 🟥 Level4

#71 readme update
  README.md
Labels: LGMSOC21, 🟩 Level1

#75 Wrong output bug fixed
  FinalProject--Python.py
Labels: LGMSOC21, 🟩 Level1

#79 Modify Contributors Section
  README.md
Labels: LGMSOC21, 🟪 Level0

#82 Hover effect added on the all buttons
  FinalProject--Python.py
Labels: LGMSOC21, 🟨 Level2

#83 Logo for Income tax Calclulator
  Income tax Calculator Logo.png
  Logo/Income tax Calculator.png
  Logo/Readme.md
Labels: LGMSOC21, 🟪 Level0

#85 LOGO FOR INCOME TAX CALCULATOR
  Logo/Income Tax calculator.png
Labels: LGMSOC21, 🟪 Level0

#86 Title corrected
  FinalProject--Python.py
Labels: LGMSOC21, 🟪 Level0

#87 Solution for #31
  FinalProject--Python.py
  learnMoreReadme.txt
Labels: LGMSOC21, 🟨 Level2

#95 Added_logos
  Logo/Tax logo1 -ambivert-sam.png
  Logo/Tax logo2 - ambivert-sam.png
Labels: LGMSOC21, 🟪 Level0

#98 Added default text in each input field
  FinalProject--Python.py
Labels: LGMSOC21, 🟨 Level2

#101 Validated Annual Tax and Exemption entered by the user.
  FinalProject--Python.py
Labels: LGMSOC21, 🟨 Level2

#102 Fixed the error of upper top closing of exit message
  FinalProject--Python.py
Labels: LGMSOC21, 🟩 Level1

#104 implemented the exit dialog button in all cases of closing
  FinalProject--Python.py
Labels: LGMSOC21, 🟨 Level2

#106 Updated learnMoreReadme.txt (Unknown Keyword Resolved)
  learnMoreReadme.txt
Labels: LGMSOC21, 🟪 Level0

#108 Added i label showing the valid entry example
  FinalProject--Python.py
Labels: LGMSOC21, 🟩 Level1

#109 Code for changing logo in title bar
  FinalProject--Python.py
  Final_Logo.gif
Labels: LGMSOC21, 🟩 Level1

#111 Fixed the unwanted text error
  FinalProject--Python.py
Labels: LGMSOC21, 🟩 Level1

#116 Added some logo
  Logo/Teal Calculator Tax Day Social Media Graphic.png
  Logo/WhatsApp Image 2021-06-16 at 14.56.25.jpeg
  Logo/WhatsApp Image 2021-06-16 at 15.10.37.jpeg
Labels: LGMSOC21, 🟪 Level0

#119 Minor Changes in Contribution Guidelines
  CONTRIBUTING.md
  README.md
Labels: LGMSOC21, 🟪 Level0

#113 Email Functionality
  FinalProject--Python.py
Labels: LGMSOC21, 🟥 Level4

#124 Added final logo to tax scheme
  FinalProject--Python.py
Labels: LGMSOC21, 🟪 Level0

#125 Implemented to share only correct details
  FinalProject--Python.py
Labels: LGMSOC21, 🟩 Level1

#127 Code for splash screen and added the gif of splash screen.
  FinalProject--Python.py
  Splash Screen.gif
Labels: LGMSOC21, 🟧 Level3

#131 Implemented Sharebutton to ask while sharing
  FinalProject--Python.py
Labels: LGMSOC21, 🟨 Level2

#133 added score card in readme
  README.md
Labels: LGMSOC21, 🟪 Level0

#139 Update FinalProject--Python.py
  FinalProject--Python.py
Labels: LGMSOC21, 🟩 Level1

#141 Added PDF status pop up
  FinalProject--Python.py
Labels: LGMSOC21, 🟩 Level1

#145 Added logo in readme
  README.md
Labels: LGMSOC21, 🟪 Level0
